export const AcademicTemplates = {
  journalManuscript: `
    <h1 style="text-align: center;">Title of the Manuscript</h1>
    <p style="text-align: center;"><b>Authors:</b> [First Name] [Last Name]<sup>1</sup>, [First Name] [Last Name]<sup>2</sup></p>
    <p style="text-align: center;"><b>Affiliations:</b> <sup>1</sup> [University Department, Institution Name, City, Country]<br><sup>2</sup> [University Department, Institution Name, City, Country]</p>
    <p style="text-align: center;"><b>Corresponding Author:</b> [Name, Email, Full Address]</p>
    <hr data-type="page-break" class="page-break">
    <h2>Abstract</h2>
    <p><b>Background:</b> Provide a structured background context.</p>
    <p><b>Methods:</b> Summarize study design and analysis.</p>
    <p><b>Results:</b> Present primary outcomes.</p>
    <p><b>Conclusions:</b> State final interpretations. Maximum 250 words.</p>
    <p><b>Keywords:</b> Keyword 1, Keyword 2, Keyword 3</p>
    <hr data-type="page-break" class="page-break">
    <h2>Introduction</h2>
    <p>State the fundamental background context, identify the knowledge gap, and explicitly declare the core hypothesis or objectives of the study.</p>
    <h2>Methods</h2>
    <h3>Study Design</h3>
    <p>Detail the experimental or observational design.</p>
    <h3>Participants</h3>
    <p>Describe the inclusion and exclusion criteria and sampling methods.</p>
    <h3>Statistical Analysis</h3>
    <p>Outline the tests used and significance thresholds (e.g., p < 0.05).</p>
    <h2>Results</h2>
    <p>Present the primary findings objectively, referencing tables and figures sequentially (e.g., Table 1, Figure 1). Do not interpret the results here.</p>
    <h2>Discussion</h2>
    <p>Interpret the results in the context of the initial hypothesis. Contrast with prior literature. State limitations of the current study design. Conclude with implications for future research.</p>
    <h2>Declarations</h2>
    <p><b>Funding:</b> [State funding sources or 'None']</p>
    <p><b>Conflicts of Interest:</b> [Declare conflicts or state 'The authors declare no conflicts of interest.']</p>
  `,
  thesis: `
    <h1 style="text-align: center;">[Thesis / Dissertation Title]</h1>
    <p style="text-align: center;">By<br><b>[Your Full Name]</b></p>
    <p style="text-align: center;"><br><br>A Thesis Submitted to [University Name] in Partial Fulfillment of the Requirements for the Degree of [Degree Name]</p>
    <p style="text-align: center;">[Month, Year]</p>
    <hr data-type="page-break" class="page-break">
    <h2>Declaration of Authorship</h2>
    <p>I declare that this thesis and the work presented in it are my own and has been generated by me as the result of my own original research.</p>
    <hr data-type="page-break" class="page-break">
    <h2>Acknowledgments</h2>
    <p>I would like to extend my sincere gratitude to my supervisor...</p>
    <hr data-type="page-break" class="page-break">
    <h2>Abstract</h2>
    <p>[A comprehensive summary of the entire thesis, usually 300-500 words.]</p>
    <hr data-type="page-break" class="page-break">
    <div data-type="index-generator" indexType="toc"></div>
    <hr data-type="page-break" class="page-break">
    <div data-type="index-generator" indexType="lof"></div>
    <hr data-type="page-break" class="page-break">
    <div data-type="index-generator" indexType="lot"></div>
    <hr data-type="page-break" class="page-break">
    <h2>Chapter 1: Introduction</h2>
    <p>Broad background and statement of the problem...</p>
    <hr data-type="page-break" class="page-break">
    <h2>Chapter 2: Literature Review</h2>
    <p>Comprehensive review of the historical context and gaps in the field...</p>
    <hr data-type="page-break" class="page-break">
    <h2>Chapter 3: Methodology</h2>
    <p>Detailed methods, materials, and procedures mapping to each specific aim...</p>
    <hr data-type="page-break" class="page-break">
    <h2>Chapter 4: Results</h2>
    <p>Outcomes of the experiments/studies...</p>
    <hr data-type="page-break" class="page-break">
    <h2>Chapter 5: Conclusion and Future Directions</h2>
    <p>Synthesis of the findings, global impact, and what needs to be done next...</p>
  `,
  systematicReview: `
    <h1 style="text-align: center;">Systematic Review and Meta-Analysis (PRISMA)</h1>
    <p style="text-align: center;"><b>Authors:</b> [Names]</p>
    <hr data-type="page-break" class="page-break">
    <h2>Abstract (PRISMA Format)</h2>
    <p><b>Background:</b> Rationale for the review.</p>
    <p><b>Objectives:</b> Explicit statement of questions being addressed.</p>
    <p><b>Eligibility Criteria:</b> Study characteristics used as criteria for eligibility.</p>
    <p><b>Sources of Evidence:</b> Databases searched and dates.</p>
    <p><b>Methods:</b> Risk of bias assessment, synthesis methods.</p>
    <p><b>Results:</b> Number of studies, participants, and main findings.</p>
    <p><b>Conclusions:</b> General interpretation of the results.</p>
    <hr data-type="page-break" class="page-break">
    <h2>1. Introduction</h2>
    <h3>1.1 Rationale</h3>
    <p>Describe the rationale for the review in the context of existing knowledge.</p>
    <h3>1.2 Objectives</h3>
    <p>Provide an explicit statement of the question(s) according to PICOS (Population, Intervention, Comparator, Outcome, Study design).</p>
    <h2>2. Methods</h2>
    <h3>2.1 Protocol and Registration</h3>
    <p>Indicate if a review protocol exists (e.g., PROSPERO).</p>
    <h3>2.2 Eligibility Criteria</h3>
    <p>Specify the study characteristics and report characteristics used as criteria.</p>
    <h3>2.3 Information Sources & Search Strategy</h3>
    <p>Describe all information sources (e.g., Medline, Embase) and present the full electronic search strategy.</p>
    <h3>2.4 Study Selection</h3>
    <p>State the process for selecting studies (e.g., two independent reviewers).</p>
    <h3>2.5 Data Extraction</h3>
    <p>Describe method of data extraction from reports.</p>
    <h3>2.6 Risk of Bias Assessment</h3>
    <p>Describe methods used for assessing risk of bias of individual studies (e.g., Cochrane RoB 2, MINORS).</p>
    <h2>3. Results</h2>
    <h3>3.1 Study Selection (PRISMA Flow)</h3>
    <p>Give numbers of studies screened, assessed for eligibility, and included in the review, with reasons for exclusions at each stage.</p>
    <h3>3.2 Study Characteristics</h3>
    <p>Present characteristics for which data were extracted.</p>
    <h3>3.3 Risk of Bias in Studies</h3>
    <p>Present data on risk of bias.</p>
    <h3>3.4 Synthesis of Results</h3>
    <p>Present main results including summary statistics and effect sizes.</p>
    <h2>4. Discussion</h2>
    <p>Summarize main findings, limitations at study and review level, and conclusions.</p>
  `,
  protocol: `
    <h1>Clinical or Laboratory Protocol</h1>
    <h2>Objective</h2>
    <p>To explicitly evaluate or determine [Objective].</p>
    <h2>Scope</h2>
    <p>This standard operating procedure (SOP) applies to all personnel performing [Task].</p>
    <h2>Safety & Precautions</h2>
    <p>Wear appropriate PPE including gloves, lab coats, and safety goggles. Perform work in a biosafety cabinet if required.</p>
    <h2>Materials / Equipment</h2>
    <ul>
      <li><p>[Reagent 1]</p></li>
      <li><p>[Device 2]</p></li>
    </ul>
    <h2>Procedure</h2>
    <ol>
      <li><p>Prepare the workspace and calibrate instruments.</p></li>
      <li><p>[Perform action sequence...]</p></li>
      <li><p>Clean up and record log in the registry.</p></li>
    </ol>
    <h2>Expected Results & Troubleshooting</h2>
    <p>If [Error Condition] occurs, isolate the sample and verify [Parameter].</p>
  `
};
