const { Pool } = require('pg');
require('dotenv').config();

// Connect to PostgreSQL (Supabase) via DATABASE_URL
// For local development, you can set DATABASE_URL in a .env file
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false // Required for Supabase / most cloud databases
  }
});

async function initDb() {
  try {
    // 1. Licenses
    await pool.query(`
      CREATE TABLE IF NOT EXISTS licenses (
        id TEXT PRIMARY KEY,
        license_key TEXT UNIQUE NOT NULL,
        customer_name TEXT,
        customer_email TEXT,
        organization TEXT,
        status TEXT DEFAULT 'active',
        tier TEXT DEFAULT 'full',
        max_seats INTEGER DEFAULT 1,
        current_activation_count INTEGER DEFAULT 0,
        allow_offline_grace INTEGER DEFAULT 1,
        custom_policy_json TEXT DEFAULT '{}',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        activated_at TIMESTAMP,
        expires_at TIMESTAMP,
        revoked_at TIMESTAMP,
        revoked_reason TEXT,
        notes TEXT
      )
    `);

    // 2. Activations (Devices bound to a license)
    await pool.query(`
      CREATE TABLE IF NOT EXISTS activations (
        id TEXT PRIMARY KEY,
        license_id TEXT NOT NULL,
        device_id TEXT NOT NULL,
        machine_fingerprint TEXT,
        platform TEXT,
        app_version TEXT,
        first_activated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        last_verified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        status TEXT DEFAULT 'active',
        ip_address TEXT,
        metadata_json TEXT DEFAULT '{}',
        FOREIGN KEY (license_id) REFERENCES licenses(id) ON DELETE CASCADE
      )
    `);

    // 3. Global License Policy
    await pool.query(`
      CREATE TABLE IF NOT EXISTS license_policy (
        id INTEGER PRIMARY KEY CHECK (id = 1),
        demo_project_limit INTEGER DEFAULT 3,
        demo_save_limit INTEGER DEFAULT 50,
        demo_reference_limit INTEGER DEFAULT 100,
        demo_screening_limit INTEGER DEFAULT 50,
        watermark_enabled INTEGER DEFAULT 1,
        watermark_text TEXT DEFAULT 'Demo Version - Generated by ReseolabX',
        max_demo_export_resolution TEXT DEFAULT '72dpi',
        allow_demo_advanced_exports INTEGER DEFAULT 0,
        allow_demo_premium_templates INTEGER DEFAULT 0,
        offline_grace_days INTEGER DEFAULT 30,
        reverify_after_hours INTEGER DEFAULT 72,
        support_email TEXT DEFAULT 'support@example.com',
        help_text TEXT DEFAULT 'Please contact support if you believe this license should be active.',
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);

    // Insert default policy if not exists (Postgres syntax)
    await pool.query(`
      INSERT INTO license_policy (id) VALUES (1)
      ON CONFLICT (id) DO NOTHING
    `);

    // 4. Audit Log
    await pool.query(`
      CREATE TABLE IF NOT EXISTS audit_log (
        id TEXT PRIMARY KEY,
        actor_type TEXT,
        actor_id TEXT,
        action TEXT NOT NULL,
        target_type TEXT,
        target_id TEXT,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        details_json TEXT DEFAULT '{}'
      )
    `);
    
    console.log("Database tables initialized successfully (PostgreSQL).");
  } catch (err) {
    console.error("Error initializing database tables:", err);
  }
}

// Helper query converter from SQLite (?) to Postgres ($1, $2, ...)
function convertQuery(query) {
  let count = 1;
  return query.replace(/\?/g, () => `$${count++}`);
}

// Promise wrappers to mimic previous sqlite3 behavior seamlessly
const all = async (query, params = []) => {
  const result = await pool.query(convertQuery(query), params);
  return result.rows;
};

const get = async (query, params = []) => {
  const result = await pool.query(convertQuery(query), params);
  return result.rows[0]; // Returns undefined if no row, like sqlite
};

const run = async (query, params = []) => {
  await pool.query(convertQuery(query), params);
  return true; 
};

initDb();

module.exports = { pool, all, get, run };
