const sqlite3 = require('sqlite3').verbose();
const path = require('path');
const fs = require('fs');

const dbPath = path.join(__dirname, 'license.db');
const db = new sqlite3.Database(dbPath);

function initDb() {
  db.serialize(() => {
    // 1. Licenses
    db.run(`
      CREATE TABLE IF NOT EXISTS licenses (
        id TEXT PRIMARY KEY,
        license_key TEXT UNIQUE NOT NULL,
        customer_name TEXT,
        customer_email TEXT,
        organization TEXT,
        status TEXT DEFAULT 'active',
        tier TEXT DEFAULT 'full',
        max_seats INTEGER DEFAULT 1,
        current_activation_count INTEGER DEFAULT 0,
        allow_offline_grace INTEGER DEFAULT 1,
        custom_policy_json TEXT DEFAULT '{}',
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        activated_at DATETIME,
        expires_at DATETIME,
        revoked_at DATETIME,
        revoked_reason TEXT,
        notes TEXT
      )
    `);

    // 2. Activations (Devices bound to a license)
    db.run(`
      CREATE TABLE IF NOT EXISTS activations (
        id TEXT PRIMARY KEY,
        license_id TEXT NOT NULL,
        device_id TEXT NOT NULL,
        machine_fingerprint TEXT,
        platform TEXT,
        app_version TEXT,
        first_activated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        last_verified_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        status TEXT DEFAULT 'active',
        ip_address TEXT,
        metadata_json TEXT DEFAULT '{}',
        FOREIGN KEY (license_id) REFERENCES licenses(id) ON DELETE CASCADE
      )
    `);

    // 3. Global License Policy
    db.run(`
      CREATE TABLE IF NOT EXISTS license_policy (
        id INTEGER PRIMARY KEY CHECK (id = 1),
        demo_project_limit INTEGER DEFAULT 3,
        demo_save_limit INTEGER DEFAULT 50,
        demo_reference_limit INTEGER DEFAULT 100,
        demo_screening_limit INTEGER DEFAULT 50,
        watermark_enabled INTEGER DEFAULT 1,
        watermark_text TEXT DEFAULT 'Demo Version - Generated by Research Desk',
        max_demo_export_resolution TEXT DEFAULT '72dpi',
        allow_demo_advanced_exports INTEGER DEFAULT 0,
        allow_demo_premium_templates INTEGER DEFAULT 0,
        offline_grace_days INTEGER DEFAULT 30,
        reverify_after_hours INTEGER DEFAULT 72,
        support_email TEXT DEFAULT 'support@example.com',
        help_text TEXT DEFAULT 'Please contact support if you believe this license should be active.',
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
      )
    `);

    // Insert default policy if not exists
    db.run(`
      INSERT OR IGNORE INTO license_policy (id) VALUES (1)
    `);

    // 4. Audit Log
    db.run(`
      CREATE TABLE IF NOT EXISTS audit_log (
        id TEXT PRIMARY KEY,
        actor_type TEXT,
        actor_id TEXT,
        action TEXT NOT NULL,
        target_type TEXT,
        target_id TEXT,
        timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
        details_json TEXT DEFAULT '{}'
      )
    `);
  });
}

// Promise wrappers
const all = (query, params = []) => new Promise((resolve, reject) => {
  db.all(query, params, (err, rows) => err ? reject(err) : resolve(rows));
});

const get = (query, params = []) => new Promise((resolve, reject) => {
  db.get(query, params, (err, row) => err ? reject(err) : resolve(row));
});

const run = (query, params = []) => new Promise((resolve, reject) => {
  db.run(query, params, function(err) {
    if (err) reject(err);
    else resolve(this);
  });
});

initDb();

module.exports = { db, all, get, run };
